services:
  nestgram:
    container_name: nestgram
    build: .
    ports: 
      - "80:3000"
    env_file: .env.prod
    depends_on:
      - mysql
    command: sh -c "npx prisma db push --schema=./prisma/schema.prisma && node src/main.js"

  mysql:
    image: mysql:lts-oraclelinux9
    container_name: mysql_db
    ports:
      - "3306:3306"
    #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
